services:
  todolist:
    container_name: "simple-todolist"
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - todolist-network

  db:
    container_name: "simple-todolist-db"
    image: postgres:latest
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PSWD}
    # ports:
    #   - "${DB_PORT}:${DB_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - todolist-network

networks:
  todolist-network:
    external: true
